apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-service
  labels:
    app: loan-service
spec:
  selector:
    matchLabels:
      app: loan-service
  template:
    metadata:
      labels:
        app: loan-service
    spec:
      containers:
        - name: loan-service
          image: library-loan-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: BOOK_SERVICE_URL
              value: http://book-service:8080
